from __future__ import annotations

from enum import IntEnum, StrEnum


class ExitCode(IntEnum):
    SUCCESS = 0
    VALIDATION_ERROR = 10
    RUNTIME_ERROR = 20
    STEP_FAILED = 30
    WAITING = 40
    CANCELLED = 50
    PERSISTENCE_ERROR = 60
    CONCURRENCY_ERROR = 70
    UNSUPPORTED = 80
    INTERNAL_ERROR = 90


class ErrorCode(StrEnum):
    ERR_VALIDATION_WORKFLOW = "ERR_VALIDATION_WORKFLOW"
    ERR_VALIDATION_INPUT = "ERR_VALIDATION_INPUT"
    ERR_FILE_NOT_FOUND = "ERR_FILE_NOT_FOUND"
    ERR_YAML_PARSE = "ERR_YAML_PARSE"
    ERR_STEP_FAILED = "ERR_STEP_FAILED"
    ERR_STEP_OUTPUT_INVALID = "ERR_STEP_OUTPUT_INVALID"
    ERR_TIMEOUT = "ERR_TIMEOUT"
    ERR_PERSISTENCE = "ERR_PERSISTENCE"
    ERR_UNSUPPORTED_STEP = "ERR_UNSUPPORTED_STEP"
    ERR_FILE_EXISTS = "ERR_FILE_EXISTS"
    ERR_DUPLICATE_STEP_ID = "ERR_DUPLICATE_STEP_ID"
    ERR_RUN_NOT_FOUND = "ERR_RUN_NOT_FOUND"
    ERR_RUN_NOT_WAITING = "ERR_RUN_NOT_WAITING"
    ERR_RESUME_EVENT_MISMATCH = "ERR_RESUME_EVENT_MISMATCH"
    ERR_VALIDATION_EVENT_INPUT = "ERR_VALIDATION_EVENT_INPUT"
    ERR_INTERNAL = "ERR_INTERNAL"
